export ANSIBLE_VAULT_PASSWORD_FILE=~/.vaultpass
export EDITOR=nano
alias apb=ansible-playbook
alias ag=ansible-galaxy
alias agu='ansible-galaxy install -r requirements.yml -f'
alias hostedit='sudo nano /etc/hosts'
alias av=ansible-vault
alias reload='source ~/.bash_profile'
alias pass='lpass show --password as2008 | pbcopy'
alias clonep='git clone git@github.com:pppontusw/'
alias clonem='git clone git@github.com:Midaxo/'
